Class {
	#name : #CVGAdditionalTeachingType,
	#superclass : #CVGElementType,
	#category : #'CVGenerator-elements - types'
}

{ #category : #testing }
CVGAdditionalTeachingType >> isAtelier [
	^false
]

{ #category : #testing }
CVGAdditionalTeachingType >> isCap [
	^false
]

{ #category : #testing }
CVGAdditionalTeachingType >> isCordee [
	^false
]

{ #category : #testing }
CVGAdditionalTeachingType >> isVulga [
	^false
]
